<?php

namespace App\Services;

use App\Models\Survey;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use PhpOffice\PhpSpreadsheet\Worksheet\PageSetup;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use PhpOffice\PhpSpreadsheet\Chart\Chart;
use PhpOffice\PhpSpreadsheet\Chart\DataSeries;
use PhpOffice\PhpSpreadsheet\Chart\DataSeriesValues;
use PhpOffice\PhpSpreadsheet\Chart\Legend;
use PhpOffice\PhpSpreadsheet\Chart\PlotArea;
use PhpOffice\PhpSpreadsheet\Chart\Title;
use RuntimeException;

class SurveyAnalysisExcelService
{
    private const PRIMARY_BLUE = '1F4E78';
    private const SECONDARY_BLUE = '5B9BD5';
    private const LIGHT_BLUE = 'D9EAF7';
    private const LIGHT_YELLOW = 'FFF2CC';
    private const LIGHT_GREEN = 'E2F0D9';
    private const LIGHT_RED = 'FCE4D6';
    private const LIGHT_GRAY = 'E7E6E6';
    private const BORDER_COLOR = '808080';
    private const WHITE = 'FFFFFF';

    public function __construct(
        private SurveyAnalysisService $analysisService
    ) {}

    /**
     * Create the complete survey analysis Excel file.
     */
    public function export(Survey $survey): string
    {
        $analysis = $this->analysisService->analyze($survey);

        /*
     * Create a completely new workbook.
     */
        $spreadsheet = new Spreadsheet();

        $spreadsheet->getProperties()
            ->setCreator('Port Said University')
            ->setLastModifiedBy('Port Said University')
            ->setTitle('Course Evaluation Survey Analysis')
            ->setSubject('Course Evaluation Survey Results')
            ->setDescription(
                'Course evaluation survey analysis generated by PSU Surveys System.'
            );

        /*
     * Only one sheet containing:
     *
     * - Survey information
     * - Individual responses
     * - Question statistics
     * - Individual response analysis
     * - Overall result
     * - Respondents comments
     */
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Course Evaluation Survey');

        $this->buildResponsesSheet(
            $sheet,
            $analysis
        );

        $this->buildResponsesSheet(
            $sheet,
            $analysis
        );

        /*
        |--------------------------------------------------------------------------
        | Charts Sheet
        |--------------------------------------------------------------------------
        */
        $chartsSheet = $spreadsheet->createSheet();
        $chartsSheet->setTitle('Charts');

        $this->buildChartsSheet(
            $chartsSheet,
            $analysis
        );

        /*
        |--------------------------------------------------------------------------
        | Keep first sheet active
        |--------------------------------------------------------------------------
        */
        $spreadsheet->setActiveSheetIndex(0);

        $spreadsheet->setActiveSheetIndex(0);

        $directory = storage_path(
            'app/public/survey-analysis'
        );

        if (
            !is_dir($directory)
            && !mkdir($directory, 0755, true)
            && !is_dir($directory)
        ) {
            throw new RuntimeException(
                'Unable to create the survey analysis directory.'
            );
        }

        $fileName = sprintf(
            'course-evaluation-%d-%s.xlsx',
            $survey->id,
            now()->format('Ymd-His')
        );

        $filePath = $directory
            . DIRECTORY_SEPARATOR
            . $fileName;

        $writer = new Xlsx($spreadsheet);

        /*
 * Important:
 * Save charts inside the generated Excel file.
 */
        $writer->setIncludeCharts(true);

        /*
 * Laravel writes calculated values only.
 * No Excel formulas are used.
 */
        $writer->setPreCalculateFormulas(false);

        $writer->save($filePath);

        $spreadsheet->disconnectWorksheets();

        unset($spreadsheet);

        return $filePath;
    }

    /**
     * Build the detailed survey responses sheet.
     */
    /**
     * Build the detailed responses sheet.
     *
     * Each survey response is displayed in a separate column,
     * following the same general structure as the reference file.
     */
    private function buildResponsesSheet(
        Worksheet $sheet,
        array $analysis
    ): void {
        $sheet->setRightToLeft(true);
        $sheet->setShowGridlines(false);

        $surveyData = $analysis['survey'] ?? [];
        $responses = array_values($analysis['responses'] ?? []);
        $sections = $analysis['sections'] ?? [];

        $responsesCount = count($responses);

        /*
         * Columns:
         *
         * A      No.
         * B:H    Evaluation item
         * I:J    Section
         * K      Question code
         * L...   Individual responses
         * Next   Class Average
         * Next   # Respondents Exceeding Criteria
         * Next   % Respondents Exceeding Criteria
         * Next   Section Average
         */

        $numberColumn = 1;             // A
        $questionStartColumn = 2;      // B
        $questionEndColumn = 8;        // H
        $sectionStartColumn = 9;       // I
        $sectionEndColumn = 10;        // J
        $questionCodeColumn = 11;      // K
        $responsesStartColumn = 12;    // L

        /*
         * Keep at least one response column.
         */
        $lastResponseColumnIndex = $responsesCount > 0
            ? $responsesStartColumn + $responsesCount - 1
            : $responsesStartColumn;

        $averageColumn = $lastResponseColumnIndex + 1;
        $exceedingColumn = $lastResponseColumnIndex + 2;
        $percentageColumn = $lastResponseColumnIndex + 3;
        $sectionAverageColumn = $lastResponseColumnIndex + 4;

        $lastColumn = $this->columnLetter(
            $sectionAverageColumn
        );

        $averageColumnLetter = $this->columnLetter(
            $averageColumn
        );

        $exceedingColumnLetter = $this->columnLetter(
            $exceedingColumn
        );

        $percentageColumnLetter = $this->columnLetter(
            $percentageColumn
        );

        $sectionAverageColumnLetter = $this->columnLetter(
            $sectionAverageColumn
        );

        /*
         * General font.
         */
        $sheet->getParent()
            ->getDefaultStyle()
            ->getFont()
            ->setName('Arial')
            ->setSize(10);

        /*
         * Header area.
         */
        $sheet->mergeCells('B1:H1');
        $sheet->mergeCells('B2:H2');
        $sheet->mergeCells('B3:H3');
        $sheet->mergeCells('B4:H4');
        $sheet->mergeCells('B5:H5');

        $sheet->setCellValue(
            'B1',
            'نتيجة استطلاع رأي حول مقرر دراسي'
        );

        $academicYear = $surveyData['academic_year'] ?? '-';
        $semester = $this->semesterArabicLabel(
            $surveyData['semester'] ?? null
        );

        $sheet->setCellValue(
            'B2',
            "العام الدراسي: {$academicYear}    الفصل الدراسي: {$semester}"
        );

        $sheet->setCellValue(
            'B3',
            'القسم: ' . ($surveyData['department'] ?? '-')
                . '    المستوى: '
                . ($surveyData['level'] ?? '-')
        );

        $sheet->setCellValue(
            'B4',
            'اسم المقرر: '
                . (
                    $surveyData['course']
                    ?? $surveyData['title']
                    ?? '-'
                )
        );

        $sheet->setCellValue(
            'B5',
            'الكلية: '
                . ($surveyData['faculty'] ?? '-')
        );

        $sheet->getStyle('B1:H1')->applyFromArray([
            'font' => [
                'bold' => true,
                'size' => 15,
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_MEDIUM,
                    'color' => ['rgb' => '000000'],
                ],
            ],
        ]);

        $sheet->getStyle('B2:H5')->applyFromArray([
            'font' => [
                'bold' => true,
                'size' => 10,
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_RIGHT,
                'vertical' => Alignment::VERTICAL_CENTER,
                'wrapText' => true,
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['rgb' => '000000'],
                ],
            ],
        ]);

        /*
         * Logo areas.
         */
        $sheet->mergeCells('A1:A5');
        $sheet->mergeCells('I1:J5');

        // $this->addReportLogo(
        //     $sheet,
        //     public_path('images/psu-logo.png'),
        //     'A1',
        //     65
        // );

        // $this->addReportLogo(
        //     $sheet,
        //     public_path('images/quality-logo.png'),
        //     'I1',
        //     70
        // );

        /*
         * Survey statistics.
         */
        $statisticsLabelStart = $questionCodeColumn;
        $statisticsLabelEnd = $questionCodeColumn + 2;
        $statisticsValueColumn = $questionCodeColumn + 3;

        $statisticsLabelStartLetter = $this->columnLetter(
            $statisticsLabelStart
        );

        $statisticsLabelEndLetter = $this->columnLetter(
            $statisticsLabelEnd
        );

        $statisticsValueColumnLetter = $this->columnLetter(
            $statisticsValueColumn
        );

        for ($row = 1; $row <= 3; $row++) {
            $sheet->mergeCells(
                "{$statisticsLabelStartLetter}{$row}:"
                    . "{$statisticsLabelEndLetter}{$row}"
            );
        }

        $sheet->setCellValue(
            "{$statisticsLabelStartLetter}1",
            'عدد أسئلة الاستبيان'
        );

        $sheet->setCellValue(
            "{$statisticsValueColumnLetter}1",
            $this->countNumericQuestions($sections)
        );

        $sheet->setCellValue(
            "{$statisticsLabelStartLetter}2",
            'عدد الجهات التي أجابت'
        );

        $sheet->setCellValue(
            "{$statisticsValueColumnLetter}2",
            $responsesCount
        );

        $threshold = (float) (
            $analysis['settings']['satisfaction_threshold']
            ?? 3
        );

        $sheet->setCellValue(
            "{$statisticsLabelStartLetter}3",
            'معيار المرور'
        );

        $sheet->setCellValue(
            "{$statisticsValueColumnLetter}3",
            $threshold
        );

        $sheet->getStyle(
            "{$statisticsLabelStartLetter}1:"
                . "{$statisticsValueColumnLetter}3"
        )->applyFromArray([
            'font' => [
                'bold' => true,
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
                'wrapText' => true,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => [
                    'rgb' => 'C69AF4',
                ],
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_MEDIUM,
                    'color' => ['rgb' => '000000'],
                ],
            ],
        ]);

        /*
         * Response scale.
         *
         * This is independent of the number of submitted responses.
         * Therefore all five scale options always appear.
         */
        $scaleHeaderRow = 6;
        $scaleValuesRow = 7;

        $sheet->mergeCells(
            "A{$scaleHeaderRow}:H{$scaleValuesRow}"
        );

        $sheet->setCellValue(
            "A{$scaleHeaderRow}",
            'عناصر الاستبانة'
        );

        $sheet->getStyle(
            "A{$scaleHeaderRow}:H{$scaleValuesRow}"
        )->applyFromArray([
            'font' => [
                'bold' => true,
                'size' => 18,
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_MEDIUM,
                    'color' => ['rgb' => '000000'],
                ],
            ],
        ]);

        /*
         * Scale uses five fixed columns I:M.
         */
        $scaleStartColumn = 9;

        $scaleLabels = [
            1 => 'غير موافق بشدة',
            2 => 'غير موافق',
            3 => 'محايد',
            4 => 'موافق',
            5 => 'موافق بشدة',
        ];

        foreach ($scaleLabels as $value => $label) {
            $columnIndex = $scaleStartColumn + $value - 1;
            $column = $this->columnLetter($columnIndex);

            $sheet->setCellValue(
                "{$column}{$scaleHeaderRow}",
                $value
            );

            $sheet->setCellValue(
                "{$column}{$scaleValuesRow}",
                $label
            );

            $sheet->getStyle(
                "{$column}{$scaleValuesRow}"
            )->getAlignment()
                ->setTextRotation(90);
        }

        $scaleEndColumn = $this->columnLetter(
            $scaleStartColumn + 4
        );

        $sheet->getStyle(
            "I{$scaleHeaderRow}:{$scaleEndColumn}{$scaleValuesRow}"
        )->applyFromArray([
            'font' => [
                'bold' => true,
                'size' => 9,
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
                'wrapText' => true,
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_MEDIUM,
                    'color' => ['rgb' => '000000'],
                ],
            ],
        ]);

        /*
         * Table header.
         */
        $headerRow = 8;

        $sheet->setCellValue("A{$headerRow}", 'م');
        $sheet->mergeCells("B{$headerRow}:H{$headerRow}");
        $sheet->setCellValue("B{$headerRow}", 'عنصر التقييم');

        $sheet->mergeCells("I{$headerRow}:J{$headerRow}");
        $sheet->setCellValue("I{$headerRow}", 'المحور');

        $sheet->setCellValue("K{$headerRow}", 'السؤال');

        foreach ($responses as $responseIndex => $response) {
            $columnIndex = $responsesStartColumn + $responseIndex;
            $column = $this->columnLetter($columnIndex);

            $sheet->setCellValue(
                "{$column}{$headerRow}",
                '#' . ($responseIndex + 1)
            );
        }

        if ($responsesCount === 0) {
            $column = $this->columnLetter(
                $responsesStartColumn
            );

            $sheet->setCellValue(
                "{$column}{$headerRow}",
                '#1'
            );
        }

        $sheet->setCellValue(
            "{$averageColumnLetter}{$headerRow}",
            "Class\nAverage"
        );

        $sheet->setCellValue(
            "{$exceedingColumnLetter}{$headerRow}",
            "# respondents\nExceeding\nCriteria"
        );

        $sheet->setCellValue(
            "{$percentageColumnLetter}{$headerRow}",
            "% of\nrespondents\nExceeding\nCriteria"
        );

        $sheet->setCellValue(
            "{$sectionAverageColumnLetter}{$headerRow}",
            'متوسط المحور'
        );

        $sheet->getStyle(
            "A{$headerRow}:{$lastColumn}{$headerRow}"
        )->applyFromArray([
            'font' => [
                'bold' => true,
                'color' => [
                    'rgb' => '000000',
                ],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
                'wrapText' => true,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => [
                    'rgb' => 'A6A6A6',
                ],
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_MEDIUM,
                    'color' => ['rgb' => '000000'],
                ],
            ],
        ]);

        $sheet->getStyle(
            "{$averageColumnLetter}{$headerRow}:"
                . "{$percentageColumnLetter}{$headerRow}"
        )->getFill()
            ->setFillType(Fill::FILL_SOLID)
            ->getStartColor()
            ->setRGB('4BACC6');

        $sheet->getRowDimension($headerRow)
            ->setRowHeight(65);

        /*
         * Question rows.
         */
        $currentRow = $headerRow + 1;
        $questionRows = [];

        foreach ($sections as $sectionIndex => $section) {
            $sectionStartRow = $currentRow;
            $sectionQuestionRows = [];

            foreach (
                $section['questions'] ?? []
                as $questionIndex => $question
            ) {
                $number = $question['number']
                    ?? count($questionRows) + 1;

                $sheet->setCellValue(
                    "A{$currentRow}",
                    $number
                );

                $sheet->mergeCells(
                    "B{$currentRow}:H{$currentRow}"
                );

                $sheet->setCellValue(
                    "B{$currentRow}",
                    $question['text'] ?? ''
                );

                $sheet->setCellValue(
                    "K{$currentRow}",
                    'Q' . $number
                );

                foreach (
                    $question['individual_responses'] ?? []
                    as $responseIndex => $individualResponse
                ) {
                    $columnIndex = $responsesStartColumn
                        + $responseIndex;

                    if (
                        $columnIndex
                        > $lastResponseColumnIndex
                    ) {
                        continue;
                    }

                    $column = $this->columnLetter(
                        $columnIndex
                    );

                    $value = !empty($question['is_numeric'])
                        ? ($individualResponse['value'] ?? null)
                        : ($individualResponse['text'] ?? null);

                    $sheet->setCellValue(
                        "{$column}{$currentRow}",
                        $value
                    );
                }

                $statistics = $question['statistics'] ?? [];

                if (!empty($question['is_numeric'])) {
                    $average = $statistics['average'] ?? null;

                    $satisfiedCount =
                        $statistics['satisfied_count'] ?? 0;

                    $satisfactionPercentage =
                        $statistics['satisfaction_percentage']
                        ?? null;

                    $sheet->setCellValue(
                        "{$averageColumnLetter}{$currentRow}",
                        $average
                    );

                    $sheet->setCellValue(
                        "{$exceedingColumnLetter}{$currentRow}",
                        $satisfiedCount
                    );

                    $sheet->setCellValue(
                        "{$percentageColumnLetter}{$currentRow}",
                        is_numeric($satisfactionPercentage)
                            ? $satisfactionPercentage / 100
                            : null
                    );
                }

                $rowFill = $questionIndex % 2 === 0
                    ? 'F8CBAD'
                    : 'FFFFFF';

                $sheet->getStyle(
                    "A{$currentRow}:{$lastColumn}{$currentRow}"
                )->applyFromArray([
                    'alignment' => [
                        'horizontal' => Alignment::HORIZONTAL_CENTER,
                        'vertical' => Alignment::VERTICAL_CENTER,
                        'wrapText' => true,
                    ],
                    'fill' => [
                        'fillType' => Fill::FILL_SOLID,
                        'startColor' => [
                            'rgb' => $rowFill,
                        ],
                    ],
                    'borders' => [
                        'allBorders' => [
                            'borderStyle' => Border::BORDER_MEDIUM,
                            'color' => ['rgb' => '000000'],
                        ],
                    ],
                ]);

                $sheet->getStyle(
                    "B{$currentRow}:H{$currentRow}"
                )->getAlignment()
                    ->setHorizontal(
                        Alignment::HORIZONTAL_RIGHT
                    );

                $sheet->getStyle(
                    "B{$currentRow}:H{$currentRow}"
                )->getFont()
                    ->setBold(true);

                $sheet->getRowDimension($currentRow)
                    ->setRowHeight(30);

                $questionRows[] = $currentRow;
                $sectionQuestionRows[] = $currentRow;

                $currentRow++;
            }

            $sectionEndRow = $currentRow - 1;

            if ($sectionEndRow >= $sectionStartRow) {
                /*
                 * Merge section title vertically.
                 */
                $sheet->mergeCells(
                    "I{$sectionStartRow}:J{$sectionEndRow}"
                );

                $sheet->setCellValue(
                    "I{$sectionStartRow}",
                    $section['title'] ?? ''
                );

                $sheet->getStyle(
                    "I{$sectionStartRow}:J{$sectionEndRow}"
                )->applyFromArray([
                    'font' => [
                        'bold' => true,
                        'size' => 11,
                    ],
                    'alignment' => [
                        'horizontal' => Alignment::HORIZONTAL_CENTER,
                        'vertical' => Alignment::VERTICAL_CENTER,
                        'wrapText' => true,
                    ],
                    'fill' => [
                        'fillType' => Fill::FILL_SOLID,
                        'startColor' => [
                            'rgb' => $sectionIndex % 2 === 0
                                ? 'F8CBAD'
                                : 'FFFFFF',
                        ],
                    ],
                    'borders' => [
                        'allBorders' => [
                            'borderStyle' => Border::BORDER_MEDIUM,
                            'color' => ['rgb' => '000000'],
                        ],
                    ],
                ]);

                /*
                 * Merge section average vertically.
                 */
                $sheet->mergeCells(
                    "{$sectionAverageColumnLetter}{$sectionStartRow}:"
                        . "{$sectionAverageColumnLetter}{$sectionEndRow}"
                );

                $sectionAverage =
                    $section['statistics']['average']
                    ?? $this->calculateSectionAverage($section);

                $sheet->setCellValue(
                    "{$sectionAverageColumnLetter}{$sectionStartRow}",
                    is_numeric($sectionAverage)
                        ? $sectionAverage / 5
                        : null
                );

                $sheet->getStyle(
                    "{$sectionAverageColumnLetter}{$sectionStartRow}:"
                        . "{$sectionAverageColumnLetter}{$sectionEndRow}"
                )->applyFromArray([
                    'font' => [
                        'bold' => true,
                    ],
                    'alignment' => [
                        'horizontal' => Alignment::HORIZONTAL_CENTER,
                        'vertical' => Alignment::VERTICAL_CENTER,
                        'textRotation' => 90,
                    ],
                    'fill' => [
                        'fillType' => Fill::FILL_SOLID,
                        'startColor' => [
                            'rgb' => $sectionIndex % 2 === 0
                                ? 'F8CBAD'
                                : 'FFFFFF',
                        ],
                    ],
                    'borders' => [
                        'allBorders' => [
                            'borderStyle' => Border::BORDER_MEDIUM,
                            'color' => ['rgb' => '000000'],
                        ],
                    ],
                ]);

                $sheet->getStyle(
                    "{$sectionAverageColumnLetter}{$sectionStartRow}"
                )->getNumberFormat()
                    ->setFormatCode(
                        NumberFormat::FORMAT_PERCENTAGE_00
                    );
            }
        }

        $questionsEndRow = $currentRow - 1;

        /*
         * Individual response summary.
         */
        $summaryStartRow = $currentRow;

        $sheet->mergeCells(
            "A{$summaryStartRow}:K{$summaryStartRow}"
        );

        $sheet->setCellValue(
            "A{$summaryStartRow}",
            'Average score of each respondent'
        );

        foreach ($responses as $responseIndex => $response) {
            $column = $this->columnLetter(
                $responsesStartColumn + $responseIndex
            );

            $sheet->setCellValue(
                "{$column}{$summaryStartRow}",
                $this->calculateResponseAverage(
                    $sections,
                    $responseIndex
                )
            );
        }

        $summarySecondRow = $summaryStartRow + 1;

        $sheet->mergeCells(
            "A{$summarySecondRow}:K{$summarySecondRow}"
        );

        $sheet->setCellValue(
            "A{$summarySecondRow}",
            'Average score above criteria'
        );

        foreach ($responses as $responseIndex => $response) {
            $column = $this->columnLetter(
                $responsesStartColumn + $responseIndex
            );

            $responseAverage =
                $this->calculateResponseAverage(
                    $sections,
                    $responseIndex
                );

            $sheet->setCellValue(
                "{$column}{$summarySecondRow}",
                is_numeric($responseAverage)
                    ? round($responseAverage - $threshold, 2)
                    : null
            );
        }

        $summaryThirdRow = $summaryStartRow + 2;

        $sheet->mergeCells(
            "A{$summaryThirdRow}:K{$summaryThirdRow}"
        );

        $sheet->setCellValue(
            "A{$summaryThirdRow}",
            'Presence / Absence indicator'
        );

        foreach ($responses as $responseIndex => $response) {
            $column = $this->columnLetter(
                $responsesStartColumn + $responseIndex
            );

            $sheet->setCellValue(
                "{$column}{$summaryThirdRow}",
                $this->countResponseAnswers(
                    $sections,
                    $responseIndex
                ) > 0
                    ? 'P'
                    : 'A'
            );
        }


        $overall = $analysis['overall_statistics'] ?? [];

        $studentsExceedingCriteria = 0;

        foreach ($responses as $responseIndex => $response) {
            $responseAverage = $this->calculateResponseAverage(
                $sections,
                $responseIndex
            );

            if (
                $responseAverage !== null
                && $responseAverage >= $threshold
            ) {
                $studentsExceedingCriteria++;
            }
        }

        $studentsExceedingPercentage = $responsesCount > 0
            ? $studentsExceedingCriteria / $responsesCount
            : 0;

        $sheet->setCellValue(
            "{$averageColumnLetter}{$summaryStartRow}",
            $overall['average'] ?? null
        );

        $sheet->setCellValue(
            "{$exceedingColumnLetter}{$summaryStartRow}",
            'Average satisfaction level'
        );

        $sheet->mergeCells(
            "{$exceedingColumnLetter}{$summaryStartRow}:"
                . "{$sectionAverageColumnLetter}{$summaryStartRow}"
        );

        $sheet->setCellValue(
            "{$averageColumnLetter}{$summarySecondRow}",
            $studentsExceedingCriteria
        );

        $sheet->mergeCells(
            "{$exceedingColumnLetter}{$summarySecondRow}:"
                . "{$sectionAverageColumnLetter}{$summarySecondRow}"
        );

        $sheet->setCellValue(
            "{$exceedingColumnLetter}{$summarySecondRow}",
            'No. respondents exceeding criteria'
        );

        $sheet->setCellValue(
            "{$averageColumnLetter}{$summaryThirdRow}",
            $studentsExceedingPercentage
        );

        $sheet->mergeCells(
            "{$exceedingColumnLetter}{$summaryThirdRow}:"
                . "{$sectionAverageColumnLetter}{$summaryThirdRow}"
        );

        $sheet->setCellValue(
            "{$exceedingColumnLetter}{$summaryThirdRow}",
            '% respondents exceeding criteria'
        );

        $sheet->getStyle(
            "A{$summaryStartRow}:"
                . "{$sectionAverageColumnLetter}{$summaryThirdRow}"
        )->applyFromArray([
            'font' => [
                'bold' => true,
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
                'wrapText' => true,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => [
                    'rgb' => 'CCFFFF',
                ],
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_MEDIUM,
                    'color' => ['rgb' => '000000'],
                ],
            ],
        ]);

        $sheet->getStyle(
            "{$averageColumnLetter}{$summaryStartRow}:"
                . "{$sectionAverageColumnLetter}{$summaryThirdRow}"
        )->getFill()
            ->setFillType(Fill::FILL_SOLID)
            ->getStartColor()
            ->setRGB('4BACC6');

        /*
         * Comments beneath the report.
         */
        $commentsStartRow = $summaryThirdRow + 2;

        $lastUsedRow = $this->appendCommentsSection(
            $sheet,
            $analysis,
            $commentsStartRow,
            $lastColumn
        );

        /*
         * Number formats.
         */
        if ($questionsEndRow >= $headerRow + 1) {
            $sheet->getStyle(
                "{$averageColumnLetter}" . ($headerRow + 1)
                    . ":{$averageColumnLetter}{$questionsEndRow}"
            )->getNumberFormat()
                ->setFormatCode('0.0');

            $sheet->getStyle(
                "{$percentageColumnLetter}" . ($headerRow + 1)
                    . ":{$percentageColumnLetter}{$questionsEndRow}"
            )->getNumberFormat()
                ->setFormatCode(
                    NumberFormat::FORMAT_PERCENTAGE_0
                );
        }

        $sheet->getStyle(
            "{$averageColumnLetter}{$summaryThirdRow}"
        )->getNumberFormat()
            ->setFormatCode(
                NumberFormat::FORMAT_PERCENTAGE_0
            );

        /*
         * Column widths.
         */
        $sheet->getColumnDimension('A')->setWidth(6);

        foreach (range('B', 'H') as $column) {
            $sheet->getColumnDimension($column)
                ->setWidth(12);
        }

        $sheet->getColumnDimension('I')->setWidth(14);
        $sheet->getColumnDimension('J')->setWidth(14);
        $sheet->getColumnDimension('K')->setWidth(9);

        foreach (
            range(
                $responsesStartColumn,
                $lastResponseColumnIndex
            ) as $columnIndex
        ) {
            $sheet->getColumnDimension(
                $this->columnLetter($columnIndex)
            )->setWidth(6);
        }

        $sheet->getColumnDimension(
            $averageColumnLetter
        )->setWidth(13);

        $sheet->getColumnDimension(
            $exceedingColumnLetter
        )->setWidth(15);

        $sheet->getColumnDimension(
            $percentageColumnLetter
        )->setWidth(16);

        $sheet->getColumnDimension(
            $sectionAverageColumnLetter
        )->setWidth(8);

        /*
         * Header heights.
         */
        $sheet->getRowDimension(1)->setRowHeight(32);
        $sheet->getRowDimension(2)->setRowHeight(23);
        $sheet->getRowDimension(3)->setRowHeight(23);
        $sheet->getRowDimension(4)->setRowHeight(23);
        $sheet->getRowDimension(5)->setRowHeight(23);
        $sheet->getRowDimension(6)->setRowHeight(25);
        $sheet->getRowDimension(7)->setRowHeight(75);

        /*
         * Freeze panes below headers.
         */
        $sheet->freezePane('L9');

        /*
         * Print settings.
         */
        $sheet->getPageSetup()
            ->setOrientation(
                PageSetup::ORIENTATION_LANDSCAPE
            )
            ->setPaperSize(
                PageSetup::PAPERSIZE_A3
            )
            ->setFitToWidth(1)
            ->setFitToHeight(0);

        $sheet->getPageMargins()
            ->setTop(0.2)
            ->setBottom(0.2)
            ->setLeft(0.2)
            ->setRight(0.2);

        $sheet->getPageSetup()
            ->setRowsToRepeatAtTopByStartAndEnd(
                $headerRow,
                $headerRow
            );

        $sheet->getHeaderFooter()
            ->setOddFooter(
                '&LPort Said University'
                    . '&CPage &P of &N'
                    . '&RPSU Surveys System'
            );

        // $sheet->setPrintArea(
        //     "A1:{$lastColumn}{$lastUsedRow}"
        // );
    }

    /**
     * Build the course evaluation results summary.
     */
    private function buildSummarySheet(
        Worksheet $sheet,
        array $analysis
    ): void {
        $sheet->setRightToLeft(false);
        $sheet->setShowGridlines(false);

        $surveyData = $analysis['survey'] ?? [];
        $sections = $analysis['sections'] ?? [];
        $overall =
            $analysis['overall_statistics'] ?? [];

        $sheet->mergeCells('A1:H1');
        $sheet->setCellValue(
            'A1',
            'PORT SAID UNIVERSITY'
        );

        $sheet->getStyle('A1:H1')
            ->applyFromArray(
                $this->titleStyle(16)
            );

        $sheet->mergeCells('A2:H2');
        $sheet->setCellValue(
            'A2',
            'RESULTS OF COURSE EVALUATION SURVEY'
        );

        $sheet->getStyle('A2:H2')
            ->applyFromArray([
                'font' => [
                    'bold' => true,
                    'size' => 14,
                    'color' => [
                        'rgb' => self::PRIMARY_BLUE,
                    ],
                ],
                'alignment' => [
                    'horizontal' =>
                    Alignment::HORIZONTAL_CENTER,
                    'vertical' =>
                    Alignment::VERTICAL_CENTER,
                ],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => [
                        'rgb' => self::LIGHT_BLUE,
                    ],
                ],
            ]);

        /*
         * Survey information.
         */
        $sheet->setCellValue('A4', 'Faculty');
        $sheet->mergeCells('B4:D4');
        $sheet->setCellValue(
            'B4',
            $surveyData['faculty'] ?? '-'
        );

        $sheet->setCellValue('E4', 'Department');
        $sheet->mergeCells('F4:H4');
        $sheet->setCellValue(
            'F4',
            $surveyData['department'] ?? '-'
        );

        $sheet->setCellValue('A5', 'Course');
        $sheet->mergeCells('B5:D5');
        $sheet->setCellValue(
            'B5',
            $surveyData['course']
                ?? $surveyData['title']
                ?? '-'
        );

        $sheet->setCellValue('E5', 'Level');
        $sheet->mergeCells('F5:H5');
        $sheet->setCellValue(
            'F5',
            $surveyData['level'] ?? '-'
        );

        $sheet->setCellValue('A6', 'Semester');
        $sheet->mergeCells('B6:D6');
        $sheet->setCellValue(
            'B6',
            $this->semesterLabel(
                $surveyData['semester'] ?? null
            )
        );

        $sheet->setCellValue(
            'E6',
            'Academic Year'
        );

        $sheet->mergeCells('F6:H6');
        $sheet->setCellValue(
            'F6',
            $surveyData['academic_year'] ?? '-'
        );

        $sheet->setCellValue(
            'A7',
            'Responses'
        );

        $sheet->mergeCells('B7:D7');
        $sheet->setCellValue(
            'B7',
            $analysis['total_responses'] ?? 0
        );

        $sheet->setCellValue(
            'E7',
            'Satisfaction Threshold'
        );

        $sheet->mergeCells('F7:H7');
        $sheet->setCellValue(
            'F7',
            $analysis['settings']['satisfaction_threshold']
                ?? 3
        );

        foreach (
            ['A4:A7', 'E4:E7'] as
            $range
        ) {
            $sheet->getStyle($range)
                ->applyFromArray(
                    $this->informationLabelStyle()
                );
        }

        foreach (
            ['B4:D7', 'F4:H7'] as
            $range
        ) {
            $sheet->getStyle($range)
                ->applyFromArray(
                    $this->informationValueStyle()
                );
        }

        /*
         * Section summary table.
         */
        $headerRow = 10;

        $headers = [
            'No.',
            'Section',
            'Questions',
            'Answers',
            'Average',
            'Satisfied Respondents',
            'Satisfaction %',
            'Status',
        ];

        foreach ($headers as $index => $header) {
            $column = $this->columnLetter(
                $index + 1
            );

            $sheet->setCellValue(
                "{$column}{$headerRow}",
                $header
            );
        }

        $sheet->getStyle("A{$headerRow}:H{$headerRow}")
            ->applyFromArray(
                $this->tableHeaderStyle()
            );

        $sheet->getRowDimension($headerRow)
            ->setRowHeight(35);

        $currentRow = $headerRow + 1;

        foreach ($sections as $sectionIndex => $section) {
            $statistics =
                $section['statistics'] ?? [];

            $average =
                $statistics['average'] ?? null;

            $acceptable =
                $average !== null
                && (
                    $statistics['acceptable']
                    ?? false
                );

            $sheet->setCellValue(
                "A{$currentRow}",
                $sectionIndex + 1
            );

            $sheet->setCellValue(
                "B{$currentRow}",
                $section['title'] ?? ''
            );

            $sheet->setCellValue(
                "C{$currentRow}",
                $section['questions_count'] ?? 0
            );

            $sheet->setCellValue(
                "D{$currentRow}",
                $statistics['count'] ?? 0
            );

            $sheet->setCellValue(
                "E{$currentRow}",
                $average
            );

            $sheet->setCellValue(
                "F{$currentRow}",
                $statistics['satisfied_count'] ?? 0
            );

            $sheet->setCellValue(
                "G{$currentRow}",
                isset(
                    $statistics['satisfaction_percentage']
                )
                    ? $statistics['satisfaction_percentage'] / 100
                    : null
            );

            $sheet->setCellValue(
                "H{$currentRow}",
                $average === null
                    ? 'N/A'
                    : (
                        $acceptable
                        ? 'Acceptable'
                        : 'Not Acceptable'
                    )
            );

            $sheet->getStyle(
                "A{$currentRow}:H{$currentRow}"
            )->applyFromArray(
                $this->dataRowStyle()
            );

            $sheet->getStyle(
                "B{$currentRow}:L{$currentRow}"
            )->getAlignment()
                ->setHorizontal(
                    Alignment::HORIZONTAL_RIGHT
                )
                ->setVertical(
                    Alignment::VERTICAL_CENTER
                )
                ->setWrapText(true);

            $sheet->getStyle(
                "H{$currentRow}"
            )->getFill()
                ->setFillType(Fill::FILL_SOLID)
                ->getStartColor()
                ->setRGB(
                    $average === null
                        ? self::LIGHT_GRAY
                        : (
                            $acceptable
                            ? self::LIGHT_GREEN
                            : self::LIGHT_RED
                        )
                );

            $sheet->getRowDimension($currentRow)
                ->setRowHeight(30);

            $currentRow++;
        }

        /*
         * Overall result row.
         */
        $totalQuestions = collect($sections)
            ->sum(
                fn(array $section) =>
                $section['questions_count'] ?? 0
            );

        $sheet->mergeCells(
            "A{$currentRow}:B{$currentRow}"
        );

        $sheet->setCellValue(
            "A{$currentRow}",
            'OVERALL RESULT'
        );

        $sheet->setCellValue(
            "C{$currentRow}",
            $totalQuestions
        );

        $sheet->setCellValue(
            "D{$currentRow}",
            $overall['count'] ?? 0
        );

        $sheet->setCellValue(
            "E{$currentRow}",
            $overall['average'] ?? null
        );

        $sheet->setCellValue(
            "F{$currentRow}",
            $overall['satisfied_count'] ?? 0
        );

        $sheet->setCellValue(
            "G{$currentRow}",
            isset(
                $overall['satisfaction_percentage']
            )
                ? $overall['satisfaction_percentage'] / 100
                : null
        );

        $sheet->setCellValue(
            "H{$currentRow}",
            ($overall['acceptable'] ?? false)
                ? 'Acceptable'
                : 'Not Acceptable'
        );

        $sheet->getStyle(
            "A{$currentRow}:H{$currentRow}"
        )->applyFromArray(
            $this->overallStyle()
        );

        $overallRow = $currentRow;

        /*
         * Overall indicators.
         */
        $currentRow += 3;

        $sheet->mergeCells(
            "A{$currentRow}:H{$currentRow}"
        );

        $sheet->setCellValue(
            "A{$currentRow}",
            'OVERALL PERFORMANCE INDICATORS'
        );

        $sheet->getStyle(
            "A{$currentRow}:H{$currentRow}"
        )->applyFromArray(
            $this->sectionSummaryStyle()
        );

        $currentRow++;

        $indicatorHeaders = [
            'Indicator',
            'Value',
            'Interpretation',
        ];

        $sheet->mergeCells(
            "A{$currentRow}:D{$currentRow}"
        );

        $sheet->setCellValue(
            "A{$currentRow}",
            $indicatorHeaders[0]
        );

        $sheet->mergeCells(
            "E{$currentRow}:F{$currentRow}"
        );

        $sheet->setCellValue(
            "E{$currentRow}",
            $indicatorHeaders[1]
        );

        $sheet->mergeCells(
            "G{$currentRow}:H{$currentRow}"
        );

        $sheet->setCellValue(
            "G{$currentRow}",
            $indicatorHeaders[2]
        );

        $sheet->getStyle(
            "A{$currentRow}:H{$currentRow}"
        )->applyFromArray(
            $this->tableHeaderStyle()
        );

        $indicatorRows = [
            [
                'Overall Average',
                $overall['average'] ?? null,
                $this->averageInterpretation(
                    $overall['average'] ?? null
                ),
                'number',
            ],
            [
                'Overall Satisfaction',
                isset(
                    $overall['satisfaction_percentage']
                )
                    ? $overall['satisfaction_percentage'] / 100
                    : null,
                $this->percentageInterpretation(
                    $overall['satisfaction_percentage'] ?? null
                ),
                'percentage',
            ],
            [
                'Satisfied Answers',
                $overall['satisfied_count'] ?? 0,
                'Number of answers meeting the satisfaction threshold.',
                'integer',
            ],
            [
                'Total Numeric Answers',
                $overall['count'] ?? 0,
                'Total numeric answers used in the analysis.',
                'integer',
            ],
        ];

        foreach ($indicatorRows as $indicator) {
            $currentRow++;

            $sheet->mergeCells(
                "A{$currentRow}:D{$currentRow}"
            );

            $sheet->setCellValue(
                "A{$currentRow}",
                $indicator[0]
            );

            $sheet->mergeCells(
                "E{$currentRow}:F{$currentRow}"
            );

            $sheet->setCellValue(
                "E{$currentRow}",
                $indicator[1]
            );

            $sheet->mergeCells(
                "G{$currentRow}:H{$currentRow}"
            );

            $sheet->setCellValue(
                "G{$currentRow}",
                $indicator[2]
            );

            $sheet->getStyle(
                "A{$currentRow}:H{$currentRow}"
            )->applyFromArray(
                $this->dataRowStyle()
            );

            if ($indicator[3] === 'percentage') {
                $sheet->getStyle(
                    "E{$currentRow}:F{$currentRow}"
                )->getNumberFormat()
                    ->setFormatCode(
                        NumberFormat::FORMAT_PERCENTAGE_00
                    );
            }

            if ($indicator[3] === 'number') {
                $sheet->getStyle(
                    "E{$currentRow}:F{$currentRow}"
                )->getNumberFormat()
                    ->setFormatCode('0.00');
            }
        }

        /*
         * Number formats.
         */
        $sheet->getStyle(
            "E11:E{$overallRow}"
        )->getNumberFormat()
            ->setFormatCode('0.00');

        $sheet->getStyle(
            "G11:G{$overallRow}"
        )->getNumberFormat()
            ->setFormatCode(
                NumberFormat::FORMAT_PERCENTAGE_00
            );

        /*
         * Column widths.
         */
        $sheet->getColumnDimension('A')
            ->setWidth(8);

        $sheet->getColumnDimension('B')
            ->setWidth(42);

        $sheet->getColumnDimension('C')
            ->setWidth(13);

        $sheet->getColumnDimension('D')
            ->setWidth(13);

        $sheet->getColumnDimension('E')
            ->setWidth(13);

        $sheet->getColumnDimension('F')
            ->setWidth(19);

        $sheet->getColumnDimension('G')
            ->setWidth(17);

        $sheet->getColumnDimension('H')
            ->setWidth(19);

        $sheet->freezePane('A11');

        /*
         * Print settings.
         */
        $sheet->getPageSetup()
            ->setOrientation(
                PageSetup::ORIENTATION_LANDSCAPE
            )
            ->setPaperSize(
                PageSetup::PAPERSIZE_A4
            )
            ->setFitToWidth(1)
            ->setFitToHeight(0);

        $sheet->getPageMargins()
            ->setTop(0.5)
            ->setBottom(0.5)
            ->setLeft(0.4)
            ->setRight(0.4);

        $sheet->getHeaderFooter()
            ->setOddFooter(
                '&LPort Said University'
                    . '&CPage &P of &N'
                    . '&RPSU Surveys System'
            );

        $sheet->getStyle(
            "A1:H{$currentRow}"
        )->getFont()
            ->setName('Arial')
            ->setSize(10);
    }
    /**
     * Build charts sheet.
     *
     * Two charts are created for each survey section:
     * 1. Class Average
     * 2. % respondents Exceeding Criteria
     */
    private function buildChartsSheet(
        Worksheet $sheet,
        array $analysis
    ): void {
        $sheet->setRightToLeft(false);
        $sheet->setShowGridlines(false);

        $sections = $analysis['sections'] ?? [];

        /*
    |--------------------------------------------------------------------------
    | Page title
    |--------------------------------------------------------------------------
    */

        $sheet->mergeCells('A1:P1');

        $sheet->setCellValue(
            'A1',
            'COURSE EVALUATION SURVEY CHARTS'
        );

        $sheet->getStyle('A1:P1')
            ->applyFromArray([
                'font' => [
                    'bold' => true,
                    'size' => 16,
                    'color' => [
                        'rgb' => self::WHITE,
                    ],
                ],
                'alignment' => [
                    'horizontal' =>
                    Alignment::HORIZONTAL_CENTER,
                    'vertical' =>
                    Alignment::VERTICAL_CENTER,
                ],
                'fill' => [
                    'fillType' =>
                    Fill::FILL_SOLID,
                    'startColor' => [
                        'rgb' =>
                        self::PRIMARY_BLUE,
                    ],
                ],
            ]);

        $sheet->getRowDimension(1)
            ->setRowHeight(28);

        /*
    |--------------------------------------------------------------------------
    | Data area used by charts
    |--------------------------------------------------------------------------
    |
    | R = Question
    | S = Average
    | T = Satisfaction %
    |
    */

        $questionColumn = 'R';
        $averageColumn = 'S';
        $percentageColumn = 'T';

        $dataRow = 3;

        /*
     * First pair of charts starts from row 3.
     */
        $chartTopRow = 3;

        /*
     * Approximate chart height.
     */
        $chartHeight = 20;

        $chartIndex = 1;

        foreach ($sections as $sectionIndex => $section) {

            /*
         * Numeric questions only.
         */
            $numericQuestions = array_values(
                array_filter(
                    $section['questions'] ?? [],
                    fn(array $question) =>
                    !empty($question['is_numeric'])
                )
            );

            if (empty($numericQuestions)) {
                continue;
            }

            $sectionTitle =
                $section['title']
                ?? 'Section ' . ($sectionIndex + 1);

            /*
        |--------------------------------------------------------------------------
        | Helper data table
        |--------------------------------------------------------------------------
        */

            $sheet->setCellValue(
                "{$questionColumn}{$dataRow}",
                'Question'
            );

            $sheet->setCellValue(
                "{$averageColumn}{$dataRow}",
                'Class Average'
            );

            $sheet->setCellValue(
                "{$percentageColumn}{$dataRow}",
                '% Respondents Exceeding Criteria'
            );

            $sheet->getStyle(
                "{$questionColumn}{$dataRow}:{$percentageColumn}{$dataRow}"
            )->applyFromArray([
                'font' => [
                    'bold' => true,
                ],
                'fill' => [
                    'fillType' =>
                    Fill::FILL_SOLID,
                    'startColor' => [
                        'rgb' =>
                        self::LIGHT_BLUE,
                    ],
                ],
                'borders' => [
                    'allBorders' => [
                        'borderStyle' =>
                        Border::BORDER_THIN,
                        'color' => [
                            'rgb' =>
                            self::BORDER_COLOR,
                        ],
                    ],
                ],
            ]);

            $dataRow++;

            $firstDataRow = $dataRow;

            foreach (
                $numericQuestions as
                $questionIndex => $question
            ) {
                $statistics =
                    $question['statistics'] ?? [];

                $questionNumber =
                    $question['number']
                    ?? ($questionIndex + 1);

                /*
             * Q1, Q2, Q3...
             */
                $sheet->setCellValue(
                    "{$questionColumn}{$dataRow}",
                    'Q' . $questionNumber
                );

                /*
             * Average from 1 to 5.
             */
                $sheet->setCellValue(
                    "{$averageColumn}{$dataRow}",
                    is_numeric(
                        $statistics['average'] ?? null
                    )
                        ? (float) $statistics['average']
                        : 0
                );

                /*
             * Satisfaction percentage from 0 to 100.
             */
                $sheet->setCellValue(
                    "{$percentageColumn}{$dataRow}",
                    is_numeric(
                        $statistics['satisfaction_percentage'] ?? null
                    )
                        ? (float) $statistics['satisfaction_percentage']
                        : 0
                );

                $dataRow++;
            }

            $lastDataRow = $dataRow - 1;

            /*
        |--------------------------------------------------------------------------
        | Categories Q1, Q2, Q3...
        |--------------------------------------------------------------------------
        */

            $categories =
                new DataSeriesValues(
                    DataSeriesValues::DATASERIES_TYPE_STRING,

                    "'Charts'!"
                        . "\${$questionColumn}\${$firstDataRow}:"
                        . "\${$questionColumn}\${$lastDataRow}",

                    null,
                    count($numericQuestions)
                );

            /*
        |--------------------------------------------------------------------------
        | Chart 1: Class Average
        |--------------------------------------------------------------------------
        */

            $averageValues =
                new DataSeriesValues(
                    DataSeriesValues::DATASERIES_TYPE_NUMBER,

                    "'Charts'!"
                        . "\${$averageColumn}\${$firstDataRow}:"
                        . "\${$averageColumn}\${$lastDataRow}",

                    null,
                    count($numericQuestions)
                );

            $averageSeries =
                new DataSeries(
                    DataSeries::TYPE_BARCHART,
                    DataSeries::GROUPING_CLUSTERED,
                    [0],
                    [],
                    [$categories],
                    [$averageValues]
                );

            /*
         * Vertical columns.
         */
            $averageSeries->setPlotDirection(
                DataSeries::DIRECTION_COL
            );

            $averagePlotArea =
                new PlotArea(
                    null,
                    [$averageSeries]
                );

            $averageChart =
                new Chart(
                    'average_chart_' . $chartIndex,
                    new Title(
                        $sectionTitle
                            . ' - Class Average'
                    ),
                    null,
                    $averagePlotArea
                );

            /*
         * Left chart.
         */
            $averageChart->setTopLeftPosition(
                'A' . $chartTopRow
            );

            $averageChart->setBottomRightPosition(
                'H'
                    . (
                        $chartTopRow
                        + $chartHeight
                    )
            );

            $sheet->addChart(
                $averageChart
            );

            /*
        |--------------------------------------------------------------------------
        | Chart 2: % Respondents Exceeding Criteria
        |--------------------------------------------------------------------------
        */

            $percentageValues =
                new DataSeriesValues(
                    DataSeriesValues::DATASERIES_TYPE_NUMBER,

                    "'Charts'!"
                        . "\${$percentageColumn}\${$firstDataRow}:"
                        . "\${$percentageColumn}\${$lastDataRow}",

                    null,
                    count($numericQuestions)
                );

            $percentageSeries =
                new DataSeries(
                    DataSeries::TYPE_BARCHART,
                    DataSeries::GROUPING_CLUSTERED,
                    [0],
                    [],
                    [$categories],
                    [$percentageValues]
                );

            $percentageSeries->setPlotDirection(
                DataSeries::DIRECTION_COL
            );

            $percentagePlotArea =
                new PlotArea(
                    null,
                    [$percentageSeries]
                );

            $percentageChart =
                new Chart(
                    'percentage_chart_' . $chartIndex,
                    new Title(
                        $sectionTitle
                            . ' - % Respondents Exceeding Criteria'
                    ),
                    null,
                    $percentagePlotArea
                );

            /*
         * Right chart.
         */
            $percentageChart->setTopLeftPosition(
                'I' . $chartTopRow
            );

            $percentageChart->setBottomRightPosition(
                'P'
                    . (
                        $chartTopRow
                        + $chartHeight
                    )
            );

            $sheet->addChart(
                $percentageChart
            );

            /*
        |--------------------------------------------------------------------------
        | Next section
        |--------------------------------------------------------------------------
        */

            $chartTopRow +=
                $chartHeight + 2;

            /*
         * Leave space between helper tables.
         */
            $dataRow += 2;

            $chartIndex++;
        }

        /*
    |--------------------------------------------------------------------------
    | Column widths
    |--------------------------------------------------------------------------
    */

        foreach (
            range('A', 'P') as
            $column
        ) {
            $sheet->getColumnDimension(
                $column
            )->setWidth(11);
        }

        $sheet->getColumnDimension('R')
            ->setWidth(12);

        $sheet->getColumnDimension('S')
            ->setWidth(16);

        $sheet->getColumnDimension('T')
            ->setWidth(28);

        /*
    |--------------------------------------------------------------------------
    | Font
    |--------------------------------------------------------------------------
    */

        $sheet->getStyle(
            'A1:T' . max(
                $dataRow,
                $chartTopRow
            )
        )->getFont()
            ->setName('Arial')
            ->setSize(10);

        /*
    |--------------------------------------------------------------------------
    | Page setup
    |--------------------------------------------------------------------------
    */

        $sheet->getPageSetup()
            ->setOrientation(
                PageSetup::ORIENTATION_LANDSCAPE
            )
            ->setPaperSize(
                PageSetup::PAPERSIZE_A3
            )
            ->setFitToWidth(1)
            ->setFitToHeight(0);

        $sheet->getPageMargins()
            ->setTop(0.3)
            ->setBottom(0.3)
            ->setLeft(0.3)
            ->setRight(0.3);

        $sheet->getHeaderFooter()
            ->setOddFooter(
                '&LPort Said University'
                    . '&CPage &P of &N'
                    . '&RPSU Surveys System'
            );
    }
    /**
     * Build the respondents comments sheet.
     */
    private function buildCommentsSheet(
        Worksheet $sheet,
        array $analysis
    ): void {
        $sheet->setRightToLeft(false);
        $sheet->setShowGridlines(false);

        $sheet->mergeCells('A1:F1');
        $sheet->setCellValue(
            'A1',
            'PORT SAID UNIVERSITY'
        );

        $sheet->getStyle('A1:F1')
            ->applyFromArray(
                $this->titleStyle(16)
            );

        $sheet->mergeCells('A2:F2');
        $sheet->setCellValue(
            'A2',
            'RESPONDENTS COMMENTS'
        );

        $sheet->getStyle('A2:F2')
            ->applyFromArray([
                'font' => [
                    'bold' => true,
                    'size' => 14,
                    'color' => [
                        'rgb' => self::PRIMARY_BLUE,
                    ],
                ],
                'alignment' => [
                    'horizontal' =>
                    Alignment::HORIZONTAL_CENTER,
                    'vertical' =>
                    Alignment::VERTICAL_CENTER,
                ],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => [
                        'rgb' => self::LIGHT_BLUE,
                    ],
                ],
            ]);

        $headers = [
            'No.',
            'Section',
            'Question No.',
            'Question',
            'Response',
            'Respondent Comment',
        ];

        $headerRow = 4;

        foreach ($headers as $index => $header) {
            $column = $this->columnLetter(
                $index + 1
            );

            $sheet->setCellValue(
                "{$column}{$headerRow}",
                $header
            );
        }

        $sheet->getStyle("A{$headerRow}:F{$headerRow}")
            ->applyFromArray(
                $this->tableHeaderStyle()
            );

        $comments = $analysis['comments'] ?? [];
        $currentRow = $headerRow + 1;

        if (empty($comments)) {
            $sheet->mergeCells(
                "A{$currentRow}:F{$currentRow}"
            );

            $sheet->setCellValue(
                "A{$currentRow}",
                'No text comments were submitted.'
            );

            $sheet->getStyle(
                "A{$currentRow}:F{$currentRow}"
            )->applyFromArray([
                'font' => [
                    'italic' => true,
                    'color' => [
                        'rgb' => '666666',
                    ],
                ],
                'alignment' => [
                    'horizontal' =>
                    Alignment::HORIZONTAL_CENTER,
                    'vertical' =>
                    Alignment::VERTICAL_CENTER,
                ],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => [
                        'rgb' => self::LIGHT_GRAY,
                    ],
                ],
                'borders' => [
                    'allBorders' => [
                        'borderStyle' =>
                        Border::BORDER_THIN,
                        'color' => [
                            'rgb' => self::BORDER_COLOR,
                        ],
                    ],
                ],
            ]);

            $sheet->getRowDimension($currentRow)
                ->setRowHeight(30);
        } else {
            foreach (
                $comments as
                $commentIndex => $comment
            ) {
                $sheet->setCellValue(
                    "A{$currentRow}",
                    $commentIndex + 1
                );

                $sheet->setCellValue(
                    "B{$currentRow}",
                    $comment['section'] ?? ''
                );

                $sheet->setCellValue(
                    "C{$currentRow}",
                    $comment['question_number'] ?? ''
                );

                $sheet->setCellValue(
                    "D{$currentRow}",
                    $comment['question'] ?? ''
                );

                $sheet->setCellValue(
                    "E{$currentRow}",
                    $comment['response_label'] ?? ''
                );

                $sheet->setCellValue(
                    "F{$currentRow}",
                    $comment['comment'] ?? ''
                );

                $sheet->getStyle(
                    "A{$currentRow}:F{$currentRow}"
                )->applyFromArray(
                    $this->dataRowStyle()
                );

                $sheet->getStyle(
                    "B{$currentRow}:L{$currentRow}"
                )->getAlignment()
                    ->setHorizontal(
                        Alignment::HORIZONTAL_RIGHT
                    )
                    ->setVertical(
                        Alignment::VERTICAL_CENTER
                    )
                    ->setWrapText(true);

                $sheet->getRowDimension($currentRow)
                    ->setRowHeight(60);

                $currentRow++;
            }

            $currentRow--;
        }

        $sheet->getColumnDimension('A')
            ->setWidth(8);

        $sheet->getColumnDimension('B')
            ->setWidth(25);

        $sheet->getColumnDimension('C')
            ->setWidth(14);

        $sheet->getColumnDimension('D')
            ->setWidth(55);

        $sheet->getColumnDimension('E')
            ->setWidth(18);

        $sheet->getColumnDimension('F')
            ->setWidth(65);

        $sheet->freezePane('A5');

        $sheet->getPageSetup()
            ->setOrientation(
                PageSetup::ORIENTATION_LANDSCAPE
            )
            ->setPaperSize(
                PageSetup::PAPERSIZE_A4
            )
            ->setFitToWidth(1)
            ->setFitToHeight(0);

        $sheet->getPageMargins()
            ->setTop(0.5)
            ->setBottom(0.5)
            ->setLeft(0.4)
            ->setRight(0.4);

        $sheet->getHeaderFooter()
            ->setOddFooter(
                '&LPort Said University'
                    . '&CPage &P of &N'
                    . '&RPSU Surveys System'
            );

        $sheet->getStyle(
            "A1:F{$currentRow}"
        )->getFont()
            ->setName('Arial')
            ->setSize(10);
    }

    /**
     * Return the Excel column name for a column index.
     */
    private function columnLetter(
        int $columnIndex
    ): string {
        return Coordinate::stringFromColumnIndex(
            $columnIndex
        );
    }

    /**
     * Main report title style.
     */
    private function titleStyle(
        int $fontSize = 16
    ): array {
        return [
            'font' => [
                'bold' => true,
                'size' => $fontSize,
                'color' => [
                    'rgb' => self::WHITE,
                ],
            ],
            'alignment' => [
                'horizontal' =>
                Alignment::HORIZONTAL_CENTER,
                'vertical' =>
                Alignment::VERTICAL_CENTER,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => [
                    'rgb' => self::PRIMARY_BLUE,
                ],
            ],
        ];
    }

    /**
     * Survey information label style.
     */
    private function informationLabelStyle(): array
    {
        return [
            'font' => [
                'bold' => true,
                'color' => [
                    'rgb' => self::PRIMARY_BLUE,
                ],
            ],
            'alignment' => [
                'horizontal' =>
                Alignment::HORIZONTAL_LEFT,
                'vertical' =>
                Alignment::VERTICAL_CENTER,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => [
                    'rgb' => self::LIGHT_BLUE,
                ],
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' =>
                    Border::BORDER_THIN,
                    'color' => [
                        'rgb' => self::BORDER_COLOR,
                    ],
                ],
            ],
        ];
    }

    /**
     * Survey information value style.
     */
    private function informationValueStyle(): array
    {
        return [
            'alignment' => [
                'horizontal' =>
                Alignment::HORIZONTAL_LEFT,
                'vertical' =>
                Alignment::VERTICAL_CENTER,
                'wrapText' => true,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => [
                    'rgb' => self::WHITE,
                ],
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' =>
                    Border::BORDER_THIN,
                    'color' => [
                        'rgb' => self::BORDER_COLOR,
                    ],
                ],
            ],
        ];
    }

    /**
     * Main table header style.
     */
    private function tableHeaderStyle(): array
    {
        return [
            'font' => [
                'bold' => true,
                'color' => [
                    'rgb' => self::WHITE,
                ],
            ],
            'alignment' => [
                'horizontal' =>
                Alignment::HORIZONTAL_CENTER,
                'vertical' =>
                Alignment::VERTICAL_CENTER,
                'wrapText' => true,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => [
                    'rgb' => self::PRIMARY_BLUE,
                ],
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' =>
                    Border::BORDER_THIN,
                    'color' => [
                        'rgb' => self::WHITE,
                    ],
                ],
            ],
        ];
    }

    /**
     * Standard data row style.
     */
    private function dataRowStyle(): array
    {
        return [
            'alignment' => [
                'horizontal' =>
                Alignment::HORIZONTAL_CENTER,
                'vertical' =>
                Alignment::VERTICAL_CENTER,
                'wrapText' => true,
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' =>
                    Border::BORDER_THIN,
                    'color' => [
                        'rgb' => self::BORDER_COLOR,
                    ],
                ],
            ],
        ];
    }

    /**
     * Section summary style.
     */
    private function sectionSummaryStyle(): array
    {
        return [
            'font' => [
                'bold' => true,
                'color' => [
                    'rgb' => '375623',
                ],
            ],
            'alignment' => [
                'horizontal' =>
                Alignment::HORIZONTAL_CENTER,
                'vertical' =>
                Alignment::VERTICAL_CENTER,
                'wrapText' => true,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => [
                    'rgb' => self::LIGHT_GREEN,
                ],
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' =>
                    Border::BORDER_THIN,
                    'color' => [
                        'rgb' => self::BORDER_COLOR,
                    ],
                ],
            ],
        ];
    }

    /**
     * Overall result style.
     */
    private function overallStyle(): array
    {
        return [
            'font' => [
                'bold' => true,
                'size' => 11,
                'color' => [
                    'rgb' => '7F6000',
                ],
            ],
            'alignment' => [
                'horizontal' =>
                Alignment::HORIZONTAL_CENTER,
                'vertical' =>
                Alignment::VERTICAL_CENTER,
                'wrapText' => true,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => [
                    'rgb' => self::LIGHT_YELLOW,
                ],
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' =>
                    Border::BORDER_MEDIUM,
                    'color' => [
                        'rgb' => self::PRIMARY_BLUE,
                    ],
                ],
            ],
        ];
    }

    /**
     * Convert semester code to English.
     */
    private function semesterLabel(
        ?string $semester
    ): string {
        return match ($semester) {
            'first' => 'First Semester',
            'second' => 'Second Semester',
            'summer' => 'Summer Semester',
            default => $semester ?: '-',
        };
    }

    /**
     * Interpret the overall average.
     */
    private function averageInterpretation(
        mixed $average
    ): string {
        if (!is_numeric($average)) {
            return 'No numeric responses are available.';
        }

        $average = (float) $average;

        return match (true) {
            $average >= 4.5 =>
            'Excellent overall evaluation.',
            $average >= 4.0 =>
            'Very good overall evaluation.',
            $average >= 3.0 =>
            'Acceptable overall evaluation.',
            $average >= 2.0 =>
            'Improvement is recommended.',
            default =>
            'Significant improvement is required.',
        };
    }

    /**
     * Interpret the satisfaction percentage.
     */
    private function percentageInterpretation(
        mixed $percentage
    ): string {
        if (!is_numeric($percentage)) {
            return 'No satisfaction result is available.';
        }

        $percentage = (float) $percentage;

        return match (true) {
            $percentage >= 90 =>
            'Very high respondents satisfaction.',
            $percentage >= 75 =>
            'High respondents satisfaction.',
            $percentage >= 60 =>
            'Moderate respondents satisfaction.',
            $percentage >= 50 =>
            'Satisfaction requires improvement.',
            default =>
            'Low respondents satisfaction.',
        };
    }
    /**
     * Calculate the average score submitted by one response.
     */
    private function calculateResponseAverage(
        array $sections,
        int $responseIndex
    ): ?float {
        $values = [];

        foreach ($sections as $section) {
            foreach (
                $section['questions'] ?? [] as
                $question
            ) {
                if (empty($question['is_numeric'])) {
                    continue;
                }

                $response =
                    $question['individual_responses'][$responseIndex]
                    ?? null;

                $value = $response['value'] ?? null;

                if (
                    $value !== null
                    && $value !== ''
                    && is_numeric($value)
                ) {
                    $values[] = (float) $value;
                }
            }
        }

        if (empty($values)) {
            return null;
        }

        return round(
            array_sum($values) / count($values),
            2
        );
    }

    /**
     * Count how many numeric questions were answered
     * by one response.
     */
    private function countResponseAnswers(
        array $sections,
        int $responseIndex
    ): int {
        $count = 0;

        foreach ($sections as $section) {
            foreach (
                $section['questions'] ?? [] as
                $question
            ) {
                if (empty($question['is_numeric'])) {
                    continue;
                }

                $response =
                    $question['individual_responses'][$responseIndex]
                    ?? null;

                $value = $response['value'] ?? null;

                if (
                    $value !== null
                    && $value !== ''
                ) {
                    $count++;
                }
            }
        }

        return $count;
    }
    /**
     * Append respondents' comments to the same responses sheet.
     *
     * Returns the final used row number.
     */
    private function appendCommentsSection(
        Worksheet $sheet,
        array $analysis,
        int $startRow,
        string $lastColumn
    ): int {
        $comments = $analysis['comments'] ?? [];

        /*
     * Comments section title.
     */
        $sheet->mergeCells(
            "A{$startRow}:{$lastColumn}{$startRow}"
        );

        $sheet->setCellValue(
            "A{$startRow}",
            'RESPONDENTS COMMENTS AND TEXT RESPONSES'
        );

        $sheet->getStyle(
            "A{$startRow}:{$lastColumn}{$startRow}"
        )->applyFromArray([
            'font' => [
                'bold' => true,
                'size' => 12,
                'color' => [
                    'rgb' => self::WHITE,
                ],
            ],
            'alignment' => [
                'horizontal' =>
                Alignment::HORIZONTAL_CENTER,
                'vertical' =>
                Alignment::VERTICAL_CENTER,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => [
                    'rgb' => self::PRIMARY_BLUE,
                ],
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' =>
                    Border::BORDER_MEDIUM,
                    'color' => [
                        'rgb' => self::PRIMARY_BLUE,
                    ],
                ],
            ],
        ]);

        $sheet->getRowDimension($startRow)
            ->setRowHeight(28);

        /*
     * Comments table header.
     */
        $headerRow = $startRow + 1;

        /*
     * Layout:
     *
     * A       No.
     * B:D     Section
     * E       Question No.
     * F:J     Question
     * K:M     Response
     * N:last  Comment
     */
        $sheet->setCellValue(
            "A{$headerRow}",
            'No.'
        );

        $sheet->mergeCells(
            "B{$headerRow}:D{$headerRow}"
        );

        $sheet->setCellValue(
            "B{$headerRow}",
            'Section'
        );

        $sheet->setCellValue(
            "E{$headerRow}",
            'Question No.'
        );

        $sheet->mergeCells(
            "F{$headerRow}:J{$headerRow}"
        );

        $sheet->setCellValue(
            "F{$headerRow}",
            'Question'
        );

        /*
     * Make sure the comment table works even when
     * the workbook contains fewer response columns.
     */
        $lastColumnIndex =
            Coordinate::columnIndexFromString(
                $lastColumn
            );

        $responseStartColumnIndex = 11; // K

        $responseEndColumnIndex = min(
            13,
            $lastColumnIndex - 1
        );

        if (
            $responseEndColumnIndex
            < $responseStartColumnIndex
        ) {
            $responseEndColumnIndex =
                $responseStartColumnIndex;
        }

        $responseStartColumn =
            Coordinate::stringFromColumnIndex(
                $responseStartColumnIndex
            );

        $responseEndColumn =
            Coordinate::stringFromColumnIndex(
                $responseEndColumnIndex
            );

        if (
            $responseStartColumnIndex
            < $responseEndColumnIndex
        ) {
            $sheet->mergeCells(
                "{$responseStartColumn}{$headerRow}:"
                    . "{$responseEndColumn}{$headerRow}"
            );
        }

        $sheet->setCellValue(
            "{$responseStartColumn}{$headerRow}",
            'Response'
        );

        $commentStartColumnIndex =
            $responseEndColumnIndex + 1;

        if (
            $commentStartColumnIndex
            > $lastColumnIndex
        ) {
            $commentStartColumnIndex =
                $lastColumnIndex;
        }

        $commentStartColumn =
            Coordinate::stringFromColumnIndex(
                $commentStartColumnIndex
            );

        if (
            $commentStartColumnIndex
            < $lastColumnIndex
        ) {
            $sheet->mergeCells(
                "{$commentStartColumn}{$headerRow}:"
                    . "{$lastColumn}{$headerRow}"
            );
        }

        $sheet->setCellValue(
            "{$commentStartColumn}{$headerRow}",
            'Respondents Comment'
        );

        $sheet->getStyle(
            "A{$headerRow}:{$lastColumn}{$headerRow}"
        )->applyFromArray(
            $this->tableHeaderStyle()
        );

        $sheet->getRowDimension($headerRow)
            ->setRowHeight(35);

        $currentRow = $headerRow + 1;

        /*
     * No comments.
     */
        if (empty($comments)) {
            $sheet->mergeCells(
                "A{$currentRow}:{$lastColumn}{$currentRow}"
            );

            $sheet->setCellValue(
                "A{$currentRow}",
                'No text comments were submitted.'
            );

            $sheet->getStyle(
                "A{$currentRow}:{$lastColumn}{$currentRow}"
            )->applyFromArray([
                'font' => [
                    'italic' => true,
                    'color' => [
                        'rgb' => '666666',
                    ],
                ],
                'alignment' => [
                    'horizontal' =>
                    Alignment::HORIZONTAL_CENTER,
                    'vertical' =>
                    Alignment::VERTICAL_CENTER,
                ],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => [
                        'rgb' => self::LIGHT_GRAY,
                    ],
                ],
                'borders' => [
                    'allBorders' => [
                        'borderStyle' =>
                        Border::BORDER_THIN,
                        'color' => [
                            'rgb' =>
                            self::BORDER_COLOR,
                        ],
                    ],
                ],
            ]);

            $sheet->getRowDimension($currentRow)
                ->setRowHeight(30);

            return $currentRow;
        }

        /*
     * Write comments.
     */
        foreach (
            $comments as
            $commentIndex => $comment
        ) {
            $sheet->setCellValue(
                "A{$currentRow}",
                $commentIndex + 1
            );

            $sheet->mergeCells(
                "B{$currentRow}:D{$currentRow}"
            );

            $sheet->setCellValue(
                "B{$currentRow}",
                $comment['section'] ?? ''
            );

            $sheet->setCellValue(
                "E{$currentRow}",
                $comment['question_number'] ?? ''
            );

            $sheet->mergeCells(
                "F{$currentRow}:J{$currentRow}"
            );

            $sheet->setCellValue(
                "F{$currentRow}",
                $comment['question'] ?? ''
            );

            if (
                $responseStartColumnIndex
                < $responseEndColumnIndex
            ) {
                $sheet->mergeCells(
                    "{$responseStartColumn}{$currentRow}:"
                        . "{$responseEndColumn}{$currentRow}"
                );
            }

            $sheet->setCellValue(
                "{$responseStartColumn}{$currentRow}",
                $comment['response_label'] ?? ''
            );

            if (
                $commentStartColumnIndex
                < $lastColumnIndex
            ) {
                $sheet->mergeCells(
                    "{$commentStartColumn}{$currentRow}:"
                        . "{$lastColumn}{$currentRow}"
                );
            }

            $sheet->setCellValue(
                "{$commentStartColumn}{$currentRow}",
                $comment['comment'] ?? ''
            );

            $sheet->getStyle(
                "A{$currentRow}:{$lastColumn}{$currentRow}"
            )->applyFromArray(
                $this->dataRowStyle()
            );

            /*
         * Arabic content alignment.
         */
            $sheet->getStyle(
                "B{$currentRow}:{$lastColumn}{$currentRow}"
            )->getAlignment()
                ->setHorizontal(
                    Alignment::HORIZONTAL_RIGHT
                )
                ->setVertical(
                    Alignment::VERTICAL_CENTER
                )
                ->setWrapText(true);

            $sheet->getStyle(
                "A{$currentRow}"
            )->getAlignment()
                ->setHorizontal(
                    Alignment::HORIZONTAL_CENTER
                );

            /*
         * Alternate row background.
         */
            if ($commentIndex % 2 !== 0) {
                $sheet->getStyle(
                    "A{$currentRow}:{$lastColumn}{$currentRow}"
                )->getFill()
                    ->setFillType(
                        Fill::FILL_SOLID
                    )
                    ->getStartColor()
                    ->setRGB('F2F2F2');
            }

            $sheet->getRowDimension($currentRow)
                ->setRowHeight(60);

            $currentRow++;
        }

        return $currentRow - 1;
    }
    private function addReportLogo(
        Worksheet $sheet,
        string $path,
        string $coordinate,
        int $height = 65
    ): void {
        if (!is_file($path)) {
            return;
        }

        $drawing = new Drawing();
        $drawing->setPath($path);
        $drawing->setCoordinates($coordinate);
        $drawing->setHeight($height);
        $drawing->setOffsetX(10);
        $drawing->setOffsetY(5);
        $drawing->setWorksheet($sheet);
    }
    private function semesterArabicLabel(
        ?string $semester
    ): string {
        return match ($semester) {
            'first' => 'الفصل الدراسي الأول',
            'second' => 'الفصل الدراسي الثاني',
            'summer' => 'الفصل الصيفي',
            default => $semester ?: '-',
        };
    }
    private function countNumericQuestions(
        array $sections
    ): int {
        $count = 0;

        foreach ($sections as $section) {
            foreach (
                $section['questions'] ?? []
                as $question
            ) {
                if (!empty($question['is_numeric'])) {
                    $count++;
                }
            }
        }

        return $count;
    }
    private function calculateSectionAverage(
        array $section
    ): ?float {
        $averages = [];

        foreach (
            $section['questions'] ?? []
            as $question
        ) {
            if (empty($question['is_numeric'])) {
                continue;
            }

            $average =
                $question['statistics']['average']
                ?? null;

            if (is_numeric($average)) {
                $averages[] = (float) $average;
            }
        }

        if (empty($averages)) {
            return null;
        }

        return round(
            array_sum($averages) / count($averages),
            2
        );
    }
}
